---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: /:title ## disables post output
timezone: null
lsi: false
markdown: kramdown


### content configuration ###
title:       "Christian Deger"
keywords:    "Platform, Developer Experience, Microservices, AWS, Chief Architect, Digital Transformation, Speaker, Architecture, Christian Deger, Christian, Deger"
description: "Personal homepage of Christian Deger, Head of Platform and Architecture at RIO – a Brand of Volkswagen Truck & Bus, Organizer of Microservices Meetup Munich and international speaker"
source_link: "https://github.com/ChristianDeger/ChristianDeger.github.io"
favicon:     "img/favicon.ico"
touch_icon:  "img/apple-touch-icon.png"
google_analytics_key: ## put YOUR key here to enable tracking! (blank to disable)


### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#f8f8f8'
  blue:      '#0967b9'
  green:     '#439D0F'
  purple:    '#a8499f'
  orange:    '#fab125'
  turquoise: '#0fbfcf'

kramdown:
  auto_ids:  false
